import { Palette } from "std-widgets.slint";
export component Histogram inherits Rectangle {
    in property <[float]> data: [10, 25, 60, 90];
    in property <float> max-value: 100; // I wish this could be calculated in UI lol

    in property <color> bar-color: Palette.foreground;
    in property <length> bar-spacing: 4px;
    in property <length> bar-radius: 4px;

    property <color> text-color: Palette.foreground;
    property <color> axis-color: #888888;
    property <length> chart-border-width: 2px;
    vertical-stretch: 1;

    GridLayout {
        spacing: 12px;

        Row {
            // Y-Axis Scale
            VerticalLayout {
                width: 35px;
                alignment: space-between;

                for multiplier in [1.0, 0.75, 0.5, 0.25, 0.0]: Text {
                    text: round(root.max-value * multiplier);
                    color: root.text-color;
                    font-size: 12px;
                    horizontal-alignment: right;
                }
            }

            // Chart
            Rectangle {
                border-color: root.axis-color;
                border-width: root.chart-border-width;
                border-radius: 6px;

                // Internal padding so bars don't touch the border walls
                HorizontalLayout {
                    padding: 8px;
                    spacing: root.bar-spacing;

                    for val in root.data: TouchArea {
                        Rectangle {
                            width: 100%;
                            height: parent.height * (val / root.max-value);
                            y: parent.height - self.height;

                            background: root.bar-color;
                            border-radius: root.bar-radius;

                            animate height {
                                duration: 250ms;
                                easing: ease-in-out;
                            }
                        }
                    }
                }
            }
        }

        Row {
            // Empty spacer to push the X-axis over
            Rectangle { }

            // X-Axis Scale
            HorizontalLayout {
                height: 35px;
                alignment: space-between;

                for multiplier in [0.0, 0.25, 0.5, 0.75, 1.0]: Text {
                    text: round(root.data.length * multiplier);
                    color: root.text-color;
                    font-size: 12px;
                    horizontal-alignment: center;
                }
            }
        }
    }
}
