import { Button, StyleMetrics } from "std-widgets.slint";
import { SlidingPanel, PanelSide } from "./sliding_panel.slint";
import { RightPanelState } from "../widgets/right_panel_states.slint";
import { RustActions } from "../global/event_bus.slint";
import {
    ImageStateReq,
    ImageContainer,
    ImageStore,
} from "../global/image_data.slint";


export enum RustAction {
    None,
    OpenFile,
    SaveFile,
    ConvertColor,
    EqualizeHistogram,
}

struct ButtonAction { right-menu: RightPanelState, rust-action: RustAction}
struct SubMenuButton { label: string, requirement: ImageStateReq, action: ButtonAction}
struct MenuButton { label: string, submenu: [SubMenuButton]}


export component LeftPanel inherits SlidingPanel {
    property <int> active_sub_menu: -1;
    property <[MenuButton]> main-menu-items: [
        {
            label: "File",
            submenu: [
                { label: "Open", action: { rust-action: RustAction.OpenFile } },
                {
                    label: "Save",
                    requirement: ImageStateReq.Any,
                    action: { rust-action: RustAction.SaveFile }
                },
                { label: "Duplicate", requirement: ImageStateReq.Any, action: { } }
            ],
        },
        {
            label: "Transform",
            submenu: [
                {
                    label: "Convert Colorspace",
                    requirement: ImageStateReq.Any,
                    action: { rust-action: RustAction.ConvertColor }
                },
                {
                    label: "Equalize Histogram",
                    requirement: ImageStateReq.Gray,
                    action: { rust-action: RustAction.EqualizeHistogram }
                },
                {
                    label: "Stretch Histogram",
                    requirement: ImageStateReq.Gray,
                    action: { right-menu: RightPanelState.StretchHistogram }
                },
                {
                    label: "Posterize",
                    requirement: ImageStateReq.Any,
                    action: { right-menu: RightPanelState.Posterize }
                }
            ],
        },
        {
            label: "Analyze",
            submenu: [
                {
                    label: "Histogram",
                    requirement: ImageStateReq.Gray,
                    action: { right-menu: RightPanelState.Histogram }
                },
                {
                    label: "Table",
                    requirement: ImageStateReq.Gray,
                    action: { right-menu: RightPanelState.HistogramTable }
                }
            ],
        },
    ];

    callback set-right-menu(RightPanelState);

    // Initialize SlidingPanel properties directly
    side: PanelSide.Left;
    width: 220px;

    VerticalLayout {
        padding: StyleMetrics.layout-padding;
        spacing: StyleMetrics.layout-spacing;
        alignment: start;

        HorizontalLayout {
            vertical-stretch: 0;
            alignment: space-between;
            Button {
                text: "🗙";

                clicked => {
                    root.close-panel()
                }
            }
        }

        for item[index] in root.main-menu-items: VerticalLayout {
            spacing: StyleMetrics.layout-spacing;
            //TODO: Make this look more like a submenu container while still sticking to styles :/
            Button {
                text: item.label;

                clicked => {
                    if item.submenu.length != 0 {
                        if active_sub_menu == index {
                            active_sub_menu = -1
                        } else {
                            active_sub_menu = index;
                        }
                    }
                }
            }

            Rectangle {
                clip: true;
                height: index == root.active_sub_menu ? submenu-layout.preferred-height : 0px;

                animate height {
                    duration: 300ms;
                    easing: ease-in-out;
                }

                submenu-layout := VerticalLayout {
                    padding-left: StyleMetrics.layout-padding;
                    spacing: StyleMetrics.layout-spacing;

                    for sub-item in item.submenu: Button {
                        text: sub-item.label;
                        enabled: ImageStore.is-requirement-met(sub-item.requirement);
                        clicked => {
                            if sub-item.action.right-menu != RightPanelState.KeepState {
                                set-right-menu(sub-item.action.right-menu);
                                active-sub-menu = -1;
                            }
                            if sub-item.action.rust-action == RustAction.OpenFile {
                                RustActions.open-file();
                            }
                            if sub-item.action.rust-action == RustAction.SaveFile {
                                RustActions.save-file();
                            }
                            if sub-item.action.rust-action == RustAction.ConvertColor {
                                RustActions.convert-color();
                            }
                            if sub-item.action.rust-action == RustAction.EqualizeHistogram {
                                RustActions.equalize-histogram();
                            }
                        }
                    }
                }
            }
        }
    }
}
