import {
    RustActions,
    GrayHistogramState,
    RGBHistogramState,
} from "../global/event_bus.slint";
import { Button, StyleMetrics, Slider } from "std-widgets.slint";
import { SlidingPanel, PanelSide } from "./sliding_panel.slint";
import { RightPanelState } from "../widgets/right_panel_states.slint";
import { Histogram } from "../widgets/histogram.slint";
import { HistTable } from "../widgets/hist_table.slint";

export component RightPanel inherits SlidingPanel {
    in-out property <RightPanelState> PanelState;
    property <string> title;

    side: PanelSide.Right;
    width: 750px;

    VerticalLayout {
        padding: StyleMetrics.layout-padding;
        spacing: StyleMetrics.layout-spacing;

        HorizontalLayout {
            vertical-stretch: 0;
            alignment: space-between;

            Button {
                text: "↩";

                clicked => {
                    root.close-panel();
                }
            }

            Text {
                text: title;
            }

            Button {
                text: "🗙";

                clicked => {
                    PanelState = RightPanelState.None;
                    root.close-panel();
                }
            }
        }

        if PanelState == RightPanelState.Histogram || PanelState == RightPanelState.StretchHistogram: Histogram {
            init() => {
                title = "Histogram";
                RustActions.calculate-gray-histogram()
            }
            bar-spacing: 0px;
            data: GrayHistogramState.data;
            max-value: GrayHistogramState.max-value;
            mean: GrayHistogramState.mean;
            std-dev: GrayHistogramState.std-dev;
        }

        if PanelState == RightPanelState.StretchHistogram: VerticalLayout {
            spacing: 5px;

            init() => {
                title = "Stretch histogram";
                RustActions.calculate-gray-histogram()
            }
            // Suwak dla wartości MIN
            HorizontalLayout {
                spacing: 10px;
                Text {
                    text: "Min: " + round(min-slider.value);
                    width: 60px;
                    vertical-alignment: center;
                }

                min-slider := Slider {
                    minimum: 0;
                    maximum: max-slider.value - 1;
                    value: 0;
                }
            }

            HorizontalLayout {
                spacing: 10px;
                Text {
                    text: "Max: " + round(max-slider.value);
                    width: 60px;
                    vertical-alignment: center;
                }

                max-slider := Slider {
                    minimum: min-slider.value + 1;
                    maximum: 255;
                    value: 255;
                }
            }

            Button {
                text: "Apply";
                clicked => {
                    RustActions.selective-stretch(round(min-slider.value), round(max-slider.value));
                }
            }
        }

        if PanelState == RightPanelState.HistogramTable: HistTable {
            init() => {
                title = "Table";
                RustActions.calculate-gray-histogram()
            }
            bar-spacing: 0px;
            data: GrayHistogramState.data;
            max-value: GrayHistogramState.max-value;
            mean: GrayHistogramState.mean;
            std-dev: GrayHistogramState.std-dev;
            total-pixels: GrayHistogramState.total-pixels;
        }

        if PanelState == RightPanelState.Posterize: VerticalLayout {
            spacing: 15px;
            alignment: center;
            vertical-stretch: 1;

            init() => {
                title = "Posterization";
            }

            HorizontalLayout {
                spacing: 10px;
                Text {
                    text: "Level: " + round(levels-slider.value);
                    width: 80px;
                    vertical-alignment: center;
                }

                levels-slider := Slider {
                    minimum: 2;   // Minimum 2 poziomy (czarny i biały)
                    maximum: 128; // Zbyt wysokie wartości i tak nie mają sensu wizualnego
                    value: 4;     // Domyślnie redukujemy do 4 poziomów
                }
            }

            Button {
                text: "Apply";
                clicked => {
                    RustActions.posterize(round(levels-slider.value));
                }
            }
        }
    }
}
