import {
    RustActions,
    GrayHistogramState,
    RGBHistogramState,
} from "../global/event_bus.slint";
import { Button, StyleMetrics, Slider } from "std-widgets.slint";
import { SlidingPanel, PanelSide } from "./sliding_panel.slint";
import { RightPanelState } from "../widgets/right_panel_states.slint";
import { Histogram } from "../widgets/histogram.slint";
import { HistTable } from "../widgets/hist_table.slint";

export component RightPanel inherits SlidingPanel {
    in-out property <RightPanelState> PanelState;
    property <string> title;

    side: PanelSide.Right;
    width: 750px;

    VerticalLayout {
        padding: StyleMetrics.layout-padding;
        spacing: StyleMetrics.layout-spacing;

        HorizontalLayout {
            vertical-stretch: 0;
            alignment: space-between;

            Button {
                text: "↩";

                clicked => {
                    root.close-panel();
                }
            }

            Text {
                text: title;
            }

            Button {
                text: "🗙";

                clicked => {
                    PanelState = RightPanelState.None;
                    root.close-panel();
                }
            }
        }

        if PanelState == RightPanelState.Histogram || PanelState == RightPanelState.StretchHistogram: Histogram {
            init() => {
                RustActions.calculate-gray-histogram()
            }
            bar-spacing: 0px;
            data: GrayHistogramState.data;
            max-value: GrayHistogramState.max-value;
            mean: GrayHistogramState.mean;
            std-dev: GrayHistogramState.std-dev;
        }
        if PanelState == RightPanelState.StretchHistogram: VerticalLayout {
            spacing: 5px;

            // Suwak dla wartości MIN
            HorizontalLayout {
                spacing: 10px;
    // Wyświetlanie aktualnej wartości min
                Text {
                    text: "Min: " + round(min-slider.value);
                    width: 60px;
                    vertical-alignment: center;
                }

                min-slider := Slider {
                    minimum: 0; 
        // Blokujemy maksymalne przesunięcie suwaka przed wartością MAX
        maximum: max-slider.value - 1;
                    value: 0;
                }
            }

            // Suwak dla wartości MAX
HorizontalLayout {
                spacing: 10px;
    // Wyświetlanie aktualnej wartości max
    Text {
                    text: "Max: " + round(max-slider.value);
                    width: 60px;
                    vertical-alignment: center;
                }

                max-slider := Slider { 
        // Blokujemy minimalne przesunięcie suwaka tuż za wartością MIN
        minimum: min-slider.value + 1;
                    maximum: 255;
                    value: 255;
                }
            }

            Button {
                text: "Zastosuj Selektywne";
                clicked => {
    // Przekazujemy zaokrąglone wartości z suwaków jako parametry 'int' do callbacka
    RustActions.selective-stretch(round(min-slider.value), round(max-slider.value));
                }
            }
        }

        if PanelState == RightPanelState.HistogramTable: HistTable {
            init() => {
                RustActions.calculate-gray-histogram()
            }
            bar-spacing: 0px;
            data: GrayHistogramState.data;
            max-value: GrayHistogramState.max-value;
            mean: GrayHistogramState.mean;
            std-dev: GrayHistogramState.std-dev;
            total-pixels: GrayHistogramState.total-pixels;
        }
    }
}
