export global GrayHistogramState {
    in property <[float]> data: [10, 25, 60, 90];
    in property <float> total-pixels: 1;
    in property <float> max-value: 100;
    in property <float> mean;
    in property <float> std-dev;
}

export global RGBHistogramState {
    in property <[[float]]> data: [[10, 25, 60, 90]];
    in property <[float]> max-value: [100];
}

export global ProfileLineState {
    in property <[float]> data: [0];
    in property <float> max-value: 255;
}

export global RustActions {
    callback open-file();
    callback save-file();
    callback close-file(int);
    callback convert-color();
    callback calculate-gray-histogram();
    callback calculate-RGB-histogram();
    callback equalize-histogram();
    callback skeletonize();
    callback selective-stretch(int, int, int, int);
    callback negate();
    callback convert-to-hsv();
    callback convert-to-lab();
    callback split-rgb();
    callback show-about();
    callback posterize(int);
    callback segment(int);
    callback median-filter(int);
    callback dilate(int);
    callback custom-filter(float, float, float, float, float, float, float, float, float, int);
    callback linear-filter(int, int);
    callback canny-edge(float, float);
    callback two-argument-op(int, int);
    callback two-stage-filter(float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int);
    callback morphology(int, int, int);
    callback hough-lines(float, float, int);
    callback profile-line(int, int, int, int);
    callback image-pyramid(int);
}
